name: Automated tests

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    name: Run tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable

      - name: Install dependencies and browsers
        run: |
          npm install -g playwright
          playwright install
          npm install -g newman @wdio/cli allure-commandline newman-reporter-html newman-reporter-json newman-reporter-allure
          pip install -r requirements.txt

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3

      - name: Run Postman API tests
        run: newman run ./tests/api/test.postman_collection.json -e ./tests/api/test-stand-ml.postman_environment.json --reporters cli,html,json,allure --reporter-html-export . --reporter-json-export . --reporter-allure-export allure-results --delay-request 4000
        continue-on-error: true

      - name: Run UI tests
        run: pytest --alluredir=allure-results
        continue-on-error: true

      - name: Store allure results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path:
            allure-results
          retention-days: 1

  generate-report:
    runs-on: ubuntu-latest
    needs: test

    name: Generate allure report
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'
      - run: sudo wget https://github.com/allure-framework/allure2/releases/download/2.23.1/allure-2.23.1.tgz && sudo tar -zxvf allure-2.23.1.tgz -C /opt/ && sudo ln -s /opt/allure-2.23.1/bin/allure /usr/bin/allure

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3

      - run: allure generate -c allure-results -o _site --clean --report-name 'Отчет о тестировании OmegaBI'

      - name: Store generated report
        uses: actions/upload-artifact@v3
        with:
          name: _site
          path:
            _site
          retention-days: 1

  publish-report:
    runs-on: ubuntu-latest
    needs: generate-report

    name: Report publication
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1.2.9

  save-data:
    runs-on: ubuntu-latest
    needs: publish-report

    name: Save data
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install requirements
        run: pip install -r requirements.txt

      - run: python3 db_manager.py
        continue-on-error: true

  send-email-message:
    runs-on: ubuntu-latest
    needs: save-data

    name: Send email notification
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install requirements
        run: pip install -r requirements.txt

      - run: python3 manager.py
        continue-on-error: true

  send-telegram-message:
    runs-on: ubuntu-latest
    needs: save-data

    name: Send telegram notification
    env:
      TELEGRAM_TOKEN: 7237289603:AAHPEonoSHxzvygLlXqFL-jT3N-PnPmlJ-E
      TELEGRAM_TO: 531912826, -1002189414551
    steps:
      - uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: Тестирование завершено🥳. Отчет доступен по ссылке:https://annk11.github.io/automation_testing/